version: "3.9"

services:
  server:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`sh.bnmwag.dev`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    build: .
    networks:
      - traefik-public
    ports:
      - "8080:8080"
    volumes:
      - app-data:/path/to/app/data

volumes:
  app-data:

networks:
  traefik-public:
    external: true